version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: local-test-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin0423
      POSTGRES_DB: test-db